### PR TITLE
Include requestid interceptor

### PR DESCRIPTION
**Pull request by kumaya**
- update grpc.go template to include requestid.
  - update template-bindata

### CODE REVIEW

**Comment by kumaya** [comment]
@dmacthedestroyer @ZachEddy: I noticed that while initializing new apps using atlas-cli; `dep-init` still picks up older version of atlas-app-toolkit (`v0.5.0`) which does not have all the changes.

**Comment by Evgeniy-L** [comment]
I do not see Gopkg files pointing to any version of atlas-app-toolkit and also do not see atlas-app-toolkit in currently committed vendor folder (which may worth to be removed :) ). I wonder where this dependency comes from?

**Comment by kumaya** [comment]
@Evgeniy-L  when we initialize an app using `atlas-cli init-app`, it calls `dep init` among other things. `dep` resolves the dependency for created application and create `Gopkg.toml` and `Gopkg.lock`. These files by default are picking `atlas-app-toolkit v0.5.0`. Not sure why!

**Comment by Evgeniy-L** [comment]
@kumaya, thanks for details. we may need to investigate why this happens.

**Comment by Evgeniy-L** [comment]
for me PR looks good. @ZachEddy, are you ok with the changes?

**Pull request merged**
